url: 'https://orlovic982.github.io' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '/pekara' # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

postcss:
  cache: false
  sass:

load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]